<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer' => '',
    'Answer Vi' => '',
    'Category' => '',
    'Choose one to answer' => '',
    'Content' => '',
    'Content Vi' => '',
    'Created At' => '',
    'Created By' => '',
    'Hint' => '',
    'Hint Image' => '',
    'Hint Vi' => '',
    'ID' => '',
    'Image' => '',
    'Input to answer' => '',
    'Is Compound' => '',
    'Lang' => '',
    'Options' => '',
    'Options Vi' => '',
    'Parent ID' => '',
    'Show Number Wrong Answer' => '',
    'Solution' => '',
    'Solution Vi' => '',
    'Source' => '',
    'Source ID' => '',
    'Status' => '',
    'Subject' => '',
    'Type' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Visibility' => '',
    'Voice Text' => '',
];
