<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Available Topics' => '',
    'Class ID' => '',
    'Close At' => '',
    'Created At' => '',
    'Created By' => '',
    'Description' => '',
    'Difficulty' => '',
    'Enter difficulty ...' => '',
    'Expired' => '',
    'Grade ID' => '',
    'ID' => '',
    'Inactive' => '',
    'Lang' => '',
    'Lesson ID' => '',
    'Level advance' => '',
    'Level basic' => '',
    'Mode' => '',
    'Mode do between open close' => '',
    'Mode do free' => '',
    'Open At' => '',
    'Question Count' => '',
    'Question advance count' => '',
    'Question basic count' => '',
    'Questions' => '',
    'Quiz detail' => '',
    'Quiz information' => '',
    'Quiz relation' => '',
    'Reward1' => '',
    'Reward2' => '',
    'Reward3' => '',
    'School ID' => '',
    'Selected Topics' => '',
    'Status' => '',
    'Subject' => '',
    'Title' => '',
    'Topic' => '',
    'Total Mark' => '',
    'Type' => '',
    'Type auto generate' => '',
    'Type end of lesson' => '',
    'Type generate by error question' => '',
    'Type generate by user' => '',
    'Type quiz between videos' => '',
    'Type quiz daily' => '',
    'Type quiz made by hand' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Visibility' => '',
];
