<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Author' => '',
    'Created At' => '',
    'Created By' => '',
    'ID' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Video' => '',
    'Article Category' => 'Danh mục bài viết',
    'Content' => 'Nội dung bài viết',
    'Description' => 'Mô tả',
    'Image' => 'Hình ảnh',
    'Status' => 'Trạng thái',
    'Status active' => 'Hoạt động',
    'Status not active' => 'Tạm dừng',
    'Title' => 'Tiêu đề',
    'Type' => 'Loại bài viết',
    'Type Contact' => 'Liên hệ',
    'Type Course Info' => 'Thông tin khóa học',
    'Type Guide' => 'Hướng dẫn',
    'Type Home' => 'Trang chủ',
    'Type Introduction' => 'Giới thiệu',
    'Type News' => 'Tin tức',
    'Type Payment' => 'Thanh toán',
];
