<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer Vi' => '',
    'Category' => '',
    'Content Vi' => '',
    'Created At' => '',
    'Created By' => '',
    'Hint' => 'Gợi ý đáp án',
    'Hint Image' => '',
    'Hint Vi' => 'Gợi ý đáp án',
    'ID' => '',
    'Is Compound' => '',
    'Lang' => '',
    'Options' => '',
    'Options Vi' => '',
    'Parent ID' => '',
    'Show Number Wrong Answer' => '',
    'Option Length Type' => 'Hiển thị các lựa chọn',
    'Solution Vi' => '',
    'Source' => '',
    'Source ID' => '',
    'Subject' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Visibility' => '',
    'Voice Text' => '',
    'Create Question' => '@@Tạo câu hỏi@@',
    'Description' => '@@Mô tả@@',
    'Description Vi' => '@@Mô tả tiếng việt@@',
    'List option' => '@@Danh sách đáp án@@',
    'Name' => '@@Tiêu đề@@',
    'Name Vi' => '@@Tiêu đề tiếng việt@@',
    'Answer' => 'Đáp án đúng',
    'Choose one to answer' => 'Trắc nghiệm',
    'Content' => 'Nội dung câu hỏi',
    'Image' => 'Ảnh câu hỏi',
    'Input to answer' => 'Nhập đáp án',
    'Solution' => 'Gợi ý đáp án',
    'Status' => 'Trạng thái',
    'Type' => 'Loại câu hỏi',
];
