<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Class ID' => '',
    'Close At' => '',
    'Created At' => '',
    'Created By' => '',
    'Enter difficulty ...' => '',
    'ID' => '',
    'Lang' => '',
    'Lesson ID' => '',
    'Open At' => '',
    'Question Count' => '',
    'Question advance count' => '',
    'Question basic count' => '',
    'School ID' => '',
    'Subject' => '',
    'Topic' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Visibility' => '',
    'Grade' => '@@Lớp học@@',
    'question_advance_count' => '@@Số câu hỏi nâng cao@@',
    'question_basic_count' => '@@Số câu hỏi cơ bản@@',
    'Active' => 'Đang hoạt động',
    'Available Topics' => 'Topic trong hệ thống',
    'Description' => 'Mô tả',
    'Difficulty' => 'Độ khó',
    'Expired' => 'Hết hạn',
    'Grade ID' => 'Lớp học',
    'Inactive' => 'Hết hiệu lực',
    'Level advance' => 'Nâng cao',
    'Level basic' => 'Cơ bản',
    'Mode' => 'Chế độ',
    'Mode do between open close' => 'Làm trong khoảng thời gian Open - Close',
    'Mode do free' => 'Làm bất cứ lúc nào',
    'Questions' => 'Danh sách câu hỏi',
    'Quiz detail' => 'Thông tin quiz',
    'Quiz information' => 'Thông tin bài quiz',
    'Quiz relation' => 'Các thông tin khác',
    'Reward1' => 'Điểm thưởng 1',
    'Reward2' => 'Điểm thưởng 2',
    'Reward3' => 'Điểm thưởng 3',
    'Selected Topics' => 'Topic đã được chọn',
    'Status' => 'Trạng thái',
    'Title' => 'Tiêu đề',
    'Total Mark' => 'Tổng điểm',
    'Type' => 'Thể loại',
    'Type auto generate' => 'Quiz Hệ thống tự sinh',
    'Type end of lesson' => 'Quiz cuối các lesson',
    'Type generate by error question' => 'Quiz tạo bởi các câu hỏi làm sai',
    'Type generate by user' => 'Quiz được tạo bởi người dùng',
    'Type quiz between videos' => 'Quiz giữa các video',
    'Type quiz daily' => 'Daily quiz',
    'Type quiz made by hand' => 'Quiz soạn bằng tay',
];
