<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Collapsed' => '',
    'Course' => '',
    'Created At' => '',
    'Created By' => '',
    'Description' => '',
    'Description Vi' => '',
    'Disabled' => '',
    'ID' => '',
    'Icon' => '',
    'Icon Type' => '',
    'Image' => '',
    'Lft' => '',
    'Lvl' => '',
    'Movable D' => '',
    'Movable L' => '',
    'Movable R' => '',
    'Movable U' => '',
    'Name' => '',
    'Name Vi' => '',
    'Order Number' => '',
    'Parent ID' => '',
    'Path' => '',
    'Question Basic Grade' => '',
    'Question Basic Time' => '',
    'Question Intermediate Grade' => '',
    'Question Intermediate Time' => '',
    'Readonly' => '',
    'Removable' => '',
    'Removable All' => '',
    'Rgt' => '',
    'Root' => '',
    'Selected' => '',
    'Status' => '',
    'Subject' => '',
    'Type' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Visibility' => '',
    'Visible' => '',
    'Topics' => '@@Chủ đề@@',
];
